[#fix]
= 仮想マシンに新しいSSHキーを追加する

== シナリオ

このシナリオでは、`exercise8`という名前のRHEL 9ベースの仮想マシン（VM）が現在`Running`状態です。チームは、このVMで作成されたSSHキーが失われたことを確認しました。SSHアクセスを回復するには、VMに新しいSSHキーを追加する必要があります。

=== 制約
- ユーザー`lab-user`にパスワードが設定されていないため、コンソール経由でVMにアクセスすることはできません。

- 追加する新しいSSHキーは`/home/{user}/.ssh/id_rsa.pub`にあります。

=== タスク
指定されたSSHキーを`exercise8` VMに追加し、リモートアクセスを復元するために必要な手順を実行してください。

NOTE: 主な目的は、SSH経由で仮想マシン`exercise8`へのアクセスを復元することです。


TIP: アクセス権限を確認するには、`virtctl ssh lab-user@exercise8` コマンドを使用してください。

演習8の解決手順は以下のとおりです。

=== コンソール
NOTE: この演習を解決するには、コマンドラインインターフェース（CLI）の使用を推奨します。

=== コマンドラインインターフェース（CLI）

1. ログインしていない場合は、割り当てられたユーザーアカウントを使用して`oc`コマンドでOpenShiftサーバーAPIにログインします。

.OpenShift login コマンド
[source,sh,role=execute,subs="attributes"]
----
{login_command}
----

[start=2]
2. 割り当てられたネームスペース{user}に移動します。

[source,sh,role=execute,subs="attributes"]
----
oc project namespace-{user}
----

[start=3]
3. sshが機能していないことを確認します。

[source,sh,role=execute,subs="attributes"]
----
virtctl ssh lab-user@exercise8
----

[source,subs="attributes"]
----
{"component":"portforward","level":"warning","msg":"Defaulting to type 'vmi'.\nOmitting the type in the target is deprecated.\nSpecifying the type will become mandatory with the next release.","pos":"portforward.go:243","timestamp":"202X-XX-XXTXX:XX:XX.XXXXXXZ"}
Warning: Permanently added 'vmi/exercise8.namespace-user5' (ED25519) to the list of known hosts.
lab-user@vmi/exercise8.namespace-user5: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
exit status 255
----

[start=4]
4. `virtctl` を使用して、`exercise8` 仮想マシンにユーザーの SSH キーを追加します。

[source,sh,role=execute,subs="attributes"]
----
virtctl credentials add-ssh-key \
-f /home/{user}/.ssh/id_rsa.pub \
--user lab-user --force exercise8
----

[start=5]
5. 出力は以下のようになります。


[source]
----
 Successfully added the key to secret "idrsa"
----

[start=6]
6. ポッド名を取得します

[source,sh,role=execute,subs="attributes"]
PODNAME=$(oc get pods -l kubevirt.io/domain=exercise8 \
-o NAME -n namespace-{user})

[start=7]
7. ログを確認します

[source,sh,role=execute,subs="attributes"]
----
oc logs $PODNAME -n namespace-{user} -f --tail 10
----

[start=8]
8. 仮想マシンポッドからのメッセージを待ちます

[source]
----
{"component":"virt-launcher","kind":"","level":"info","msg":"Reloading access credentials because secret changed","name":"exercise8","namespace":"namespace-{user}","pos":"access_credentials.go:448","timestamp":"2024-11-25T18:47:52.185346Z","uid":"728e56da-dff5-400d-8967-fe406e4ca72f"}
----

[start=9]
9. SSHアクセスをテストします

[source,sh,role=execute,subs="attributes"]
----
virtctl ssh lab-user@exercise8
----

=== 学習内容

この演習では、仮想マシンで動的認証情報サポートが有効になっている場合、`virtctl`を使用してRHEL-9仮想マシンにSSHキーを追加できることを学びました。